name: Generate ASCII Artwork
on:
    push

jobs:
   build_job:
    runs-on: ubuntu-latest
    steps:
    - name: Install Cowsay program
      run: sudo apt-get install cowsay -y
    
    - name: Exeute Cowsay CMD
      run: cowsay -f dragon "Run for Cover, I am a dragon ururu" >> dragon.txt

    - name: Sleep for 30 seconds
      run: sleep 30

   test_job_2:
     runs-on: ubuntu-latest
     steps:
     - name: Sleep for 10 seconds
       run: sleep 10

     - name: test File Exist
       run: grep =i "dragon" dragon.txt
   
   deploy_job_3:
      runs-on: ubuntu-latest
      steps:
      - name: Read File
        run: cat dragon.txt
      - name: Deploy
        run: Echo Deploying..in 1 2 3 done....
    
    