name: Environment variables and secrets

on:
    push
env:
        CONTAINER_REGISTRY: docker.io
        DOCKER_USERNAME: justcheck
        IMAGE_NAME: nginx1-0
jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: echo docker build -t ${{ env.CONTAINER_REGISTRY}}/$DOCKER_USERNAME/$IMAGE_NAME:latest
    - name: Docker login
      env:
        DOCKER_PASSWORD: Thi3i3Passwrd
      run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    - name: Docker Publish
      run: echo docker push $CONTAINER_REGISTRY/DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker run
      run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/DOCKER_USERNAME/$IMAGE_NAME:latest
      


